FROM tomcat:8
ADD target/*.war C:/Windows/System32/config/systemprofile/AppData/Local/Jenkins/.jenkins/workspace/usermanagement-devops/DevopS

#COPY "C:/Users/Hafsah/Downloads/apache-tomcat-8.0.9/apache-tomcat-8.0.9/webapps/usermanagement-devops.war"
CMD ["catalina.sh", "run"]
