FROM tomcat:8
ADD usermanagement-devops.war C:/Users/Hafsah/Downloads/apache-tomcat-8.0.9/apache-tomcat-8.0.9/webapps/

#COPY "C:/Users/Hafsah/Downloads/apache-tomcat-8.0.9/apache-tomcat-8.0.9/webapps/usermanagement-devops.war"
CMD ["catalina.sh", "run"]
